# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('author', models.CharField(max_length=50, null=True)),
                ('date_comment', models.DateTimeField(verbose_name='Date of published')),
            ],
        ),
        migrations.CreateModel(
            name='DiscriptionBlogers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikname', models.CharField(max_length=30)),
                ('sur_name', models.CharField(max_length=15)),
                ('firs_name', models.CharField(max_length=15)),
                ('age', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('url_instagramm', models.URLField()),
                ('url_youtube', models.URLField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='blogers')),
                ('discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=25)),
                ('mark', models.FloatField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('foto', models.ImageField(null=True, upload_to='products')),
                ('url', models.URLField()),
                ('additional_info', models.TextField()),
                ('id_comments', models.ManyToManyField(blank=True, related_name='com_product', to='btblogers.Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_video', models.DateTimeField()),
                ('video_name', models.CharField(max_length=100)),
                ('id_bad_products', models.ManyToManyField(related_name='rel_BP', to='btblogers.Products')),
                ('id_blogers', models.ManyToManyField(related_name='video', to='btblogers.DiscriptionBlogers')),
                ('id_good_products', models.ManyToManyField(related_name='rel_GP', to='btblogers.Products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='type_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='btblogers.Types'),
        ),
        migrations.AddField(
            model_name='comments',
            name='id_bloger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='btblogers.DiscriptionBlogers'),
        ),
    ]
