# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btblogers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='additional_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
