# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btblogers', '0003_auto_20160331_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url_youtube',
            field=models.URLField(default='null'),
        ),
    ]
