# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btblogers', '0004_video_url_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id_bloger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='btblogers.DiscriptionBlogers'),
        ),
        migrations.AlterField(
            model_name='discriptionblogers',
            name='age',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='discriptionblogers',
            name='city',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='discriptionblogers',
            name='country',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='discriptionblogers',
            name='sur_name',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='discriptionblogers',
            name='url_instagramm',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='additional_info',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='foto',
            field=models.ImageField(blank=True, default=b'/Users/zannasapoval/djcode/blogers/media/default.jpg', null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url_youtube',
            field=models.URLField(default=None),
        ),
    ]
