# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btblogers', '0007_auto_20160331_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='discription_video',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, upload_to='video'),
        ),
    ]
