# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btblogers', '0008_auto_20160331_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, default=b'/Users/zannasapoval/djcode/blogers/media/default_brands.jpg', null=True, upload_to='brands')),
            ],
        ),
    ]
