# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btblogers', '0009_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(blank=True, default=b'/Users/zannasapoval/djcode/blogers/media/brands/default_brands.jpg', null=True, upload_to='brands'),
        ),
        migrations.AlterField(
            model_name='products',
            name='foto',
            field=models.ImageField(blank=True, default=b'/Users/zannasapoval/djcode/blogers/media/products/default.jpg', null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id_bad_products',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='rel_BP', to='btblogers.Products'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id_good_products',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='rel_GP', to='btblogers.Products'),
        ),
    ]
