# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btblogers', '0010_auto_20160401_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id_bad_products',
            field=models.ManyToManyField(blank=True, default=None, related_name='rel_BP', to='btblogers.Products'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id_good_products',
            field=models.ManyToManyField(blank=True, default=None, related_name='rel_GP', to='btblogers.Products'),
        ),
    ]
