# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btblogers', '0012_auto_20160405_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='video'),
        ),
    ]
