# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btblogers', '0013_auto_20160405_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
    ]
